# Generated by Django 3.1.1 on 2020-09-22 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=200)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('road', models.CharField(max_length=250)),
                ('zipcode', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(max_length=250)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Commentaire')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.accomodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddAccomodation',
            fields=[
                ('addAccomodation_auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('addAccomodation_name', models.CharField(max_length=128, verbose_name='Nom')),
                ('addAccomodation_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Numéro')),
                ('addAccomodation_road', models.CharField(max_length=250, verbose_name='Adresse')),
                ('addAccomodation_zipcode', models.PositiveIntegerField(verbose_name='Code Postal')),
                ('addAccomodation_city', models.CharField(max_length=50, verbose_name='Ville')),
                ('addAccomodation_phone', models.CharField(max_length=10, verbose_name='Téléphone')),
                ('addAccomodation_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('addAccomodation_url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('addAccomodation_image', models.ImageField(blank=True, default='default_accomodation_image.jpg', null=True, upload_to='accomodation/', verbose_name='Image')),
                ('addAccomodation_description', models.CharField(max_length=250, verbose_name='Description')),
                ('addAccomodation_statut', models.CharField(choices=[('Non_lu', 'Non lu'), ('Archive', 'Archivé')], default='Non_lu', max_length=16, verbose_name='Statut de la demande')),
                ('addAccomodation_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.category', verbose_name="Categorie d'hébergement")),
                ('addAccomodation_parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.parking', verbose_name='Type de Parking')),
            ],
        ),
        migrations.AddField(
            model_name='accomodation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.category'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.parking'),
        ),
    ]
